allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - simple-icons@16.30.0
  - '@types/node@26.6.2'
  - eslint-config-xo@4.0.0
  - eslint-plugin-jsdoc@64.5.4
  - eslint-plugin-unicorn@76.0.0
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
